version: '2'
services:
    tendermanagement-app:
        image: tendermanagement
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tendermanagement-postgresql:5432/tenderManagement
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tendermanagement-postgresql:
        extends:
            file: postgresql.yml
            service: tendermanagement-postgresql
